package org.graphserver.jna;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import org.graphserver.jna.GraphserverLibrary.ListNode;
/**
 * <i>native declaration : /Users/kolohe/dev/graphserver/core/graph.h:23</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Vertex extends Structure<Vertex, Vertex.ByValue, Vertex.ByReference > {
	public int degree_out;
	public int degree_in;
	/// C type : ListNode*
	public ListNode outgoing;
	/// C type : ListNode*
	public ListNode incoming;
	/// C type : char*
	public Pointer label;
	public int deleted_neighbors;
	public Vertex() {
		super();
	}
	/**
	 * @param outgoing C type : ListNode*<br>
	 * @param incoming C type : ListNode*<br>
	 * @param label C type : char*
	 */
	public Vertex(int degree_out, int degree_in, ListNode outgoing, ListNode incoming, Pointer label, int deleted_neighbors) {
		super();
		this.degree_out = degree_out;
		this.degree_in = degree_in;
		this.outgoing = outgoing;
		this.incoming = incoming;
		this.label = label;
		this.deleted_neighbors = deleted_neighbors;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Vertex newInstance() { return new Vertex(); }
	public static Vertex[] newArray(int arrayLength) {
		return Structure.newArray(Vertex.class, arrayLength);
	}
	public static class ByReference extends Vertex implements Structure.ByReference {
		
	};
	public static class ByValue extends Vertex implements Structure.ByValue {
		
	};
}
