package org.graphserver.jna;
import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * <i>native declaration : /Users/kolohe/dev/graphserver/core/contraction.h:10</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CH extends Structure<CH, CH.ByValue, CH.ByReference > {
	/// C type : Graph*
	public org.graphserver.jna.Graph.ByReference up;
	/// C type : Graph*
	public org.graphserver.jna.Graph.ByReference down;
	public CH() {
		super();
	}
	/**
	 * @param up C type : Graph*<br>
	 * @param down C type : Graph*
	 */
	public CH(org.graphserver.jna.Graph.ByReference up, org.graphserver.jna.Graph.ByReference down) {
		super();
		this.up = up;
		this.down = down;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CH newInstance() { return new CH(); }
	public static CH[] newArray(int arrayLength) {
		return Structure.newArray(CH.class, arrayLength);
	}
	public static class ByReference extends CH implements Structure.ByReference {
		
	};
	public static class ByValue extends CH implements Structure.ByValue {
		
	};
}
